version: "3.8"

services:
  db:
    image: postgres:15
    container_name: library_system_db
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - library_system_network

  web:
    image: hetpatel26/library_system:main
    container_name: library_system_web
    restart: unless-stopped

    env_file:
      - .env

    environment:
      DB_HOST: db
      ENVIRONMENT: production

    ports:
      - "8000:8000"

    depends_on:
      - db

    networks:
      - library_system_network

volumes:
  postgres_data:

networks:
  library_system_network: