name: CI pipeline

on:
  push:
    branches: [ main ]

env:
  SECRET_KEY: ${{ vars.SECRET_KEY }}
  DEBUG: ${{ vars.DEBUG }}
  ALLOWED_HOSTS: ${{ vars.ALLOWED_HOSTS }}

  DB_NAME: ${{ vars.DB_NAME }}
  DB_USER: ${{ vars.DB_USER }}
  DB_PASSWORD: ${{ vars.DB_PASSWORD }}
  DB_PORT: ${{ vars.DB_PORT }}
  DB_HOST: ${{ vars.DB_HOST }}

jobs:
  lint:
    runs-on: ubuntu-latest
    environment: test 
  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Set Up Python
        uses: actions/setup-python@v6 
        with:
          python-version: '3.11'

      - name: Installing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint
      
      - name: Run Pylint
        run: pylint **/*.py --exit-zero

  security:
    name: Security Scanning
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set Up Python
      uses: actions/setup-python@v6 
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install safety bandit
        pip install -r requirements.txt
    
    - name: Check for security vulnerabilities
      run: safety check --json
    
    - name: Run Bandit security scan
      run: bandit -r . -f json -o bandit-report.json
    
    - name: Upload security reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: security-reports
        path: bandit-report.json

  test:
    runs-on: ubuntu-latest
    environment: test
    needs: [ lint ]

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: ${{ vars.DB_PASSWORD }}
          POSTGRES_USER: ${{ vars.DB_USER }}
          POSTGRES_DB: ${{ vars.DB_NAME }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:

    - name: Checkout repository
      uses: actions/checkout@v5
    
    - name: Set Up Python
      uses: actions/setup-python@v6 
      with:
        python-version: '3.11'

    - name: Installing dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run migrations
      env:
        SECRET_KEY: ${{ vars.SECRET_KEY }}
        DEBUG: ${{ vars.DEBUG }}
        ALLOWED_HOSTS: ${{ vars.ALLOWED_HOSTS }}
  
        DB_NAME: ${{ vars.DB_NAME }} 
        DB_USER: ${{ vars.DB_USER }}
        DB_PASSWORD: ${{ vars.DB_PASSWORD }}
        DB_HOST: ${{ vars.DB_HOST }}
        DB_PORT: 5432

      run: |
        cd Book_Library_System/library  
        python manage.py migrate

    - name: Run Tests
      run: |
        cd Book_Library_System/library/
        pytest