name: Code quality check

on:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Set Up Python
        uses: actions/setup-python@v6 
        with:
          python-version: '3.11'

      - name: Installing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 black isort pylint

      - name: Run Black (Code Formatting)
        run: black --check .
      
      - name: Run isort (Import Sorting)
        run: isort --check-only .
      
      - name: Run Flake8 (Linting)
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      
      - name: Run Pylint
        run: pylint **/*.py --exit-zero